package com.typesafe.reactiveplatform.manifest

/**
* Describes the modules contained in a "universe" of projects, related by some
* common characteristic (for instance: compiled on 2.10, or java-only, etc.)
* Each index can be automatically generated by one of the "deploy" sections.
* 
* @param modules Information about modules included in this index, including all
* necessary information to discover the module and force a revision
* in the user build.
*/
case class Index(modules: Seq[ModuleInfo])