name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - name: Test
      env:
      - JVM_OPTS="-Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxPermSize=256m"
      run: |
        sbt "^test"
        sbt "^publishLocal"
        sbt "it:test"
